server:
  port:                     8210
  servlet:
    context-path: /gateway

spring:
  cloud:
    gateway:

      metrics:
        enabled: true


management:

  endpoint:
    metrics:
      enabled: true

    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:

    web:
      exposure:
        include: "*"
    beans:
      enabled: true