###########################
# Config applicative globale
###########################
# mode jar, port et context
server:
  port:                              ${PORT:9020}





# Discovery server
eureka:
  client:
    serviceUrl:
      defaultZone:                                      http://localhost:8300/eureka/
    registerWithEureka:                                 true
    registry-fetch-interval-seconds: 3

    fetchRegistry:                                      true
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: /rentes-service/actuator/info
    healthCheckUrlPath: /rentes-service/actuator/health
    leaseInfo:
      renewalIntervalInSecs: 5
      durationInSecs: 10
    home-page-url: /rentes-service/swagger-ui.html
    lease-expiration-duration-in-seconds: 5
    leaseRenewalIntervalInSeconds: 10
