#configuration d'un autre fichier de logs, par defaut classpath:/logback.xml, ou logback.spring.xml
#logging.config=file:c://logs/conf/conf.xml
hibernate:
  driver-class-name:              org.h2.Driver
  url:                            jdbc:h2:mem:persons-schema;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username:                       sa
  password:
  dialect:                        org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto:                         create-drop
  show:
    sql:                          true


spring:
  h2:
    console:
      enabled:                    true
      path:                       /h2